/**
 * Assembles the 8086 test programs in tests/fixtures/x86 with NASM and writes
 * their bytes to tests/fixtures/x86/programs.ts, so the tests need no
 * assembler: run `bun scripts/assemble-x86-fixtures.ts` after changing one.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const directory = join(import.meta.dirname, '../tests/fixtures/x86');
const entries = readdirSync(directory)
  .filter((name) => name.endsWith('.asm'))
  .sort()
  .map((name) => {
    const output = join(directory, name.replace(/\.asm$/, '.bin'));
    execFileSync('nasm', ['-f', 'bin', join(directory, name), '-o', output]);
    const hex = Buffer.from(readFileSync(output)).toString('hex');
    execFileSync('rm', [output]);
    return `  ${JSON.stringify(name.replace(/\.asm$/, ''))}: ${JSON.stringify(hex)},`;
  });
writeFileSync(
  join(directory, 'programs.ts'),
  `// Generated by scripts/assemble-x86-fixtures.ts from the .asm files here.\nexport const PROGRAMS: Record<string, string> = {\n${entries.join('\n')}\n};\n`
);
