/**
 * Builds src/compiler/runtime/hersheyFonts.ts: the Hershey glyphs that stand
 * in for Borland's ten stroked fonts when a program has no .CHR files.
 *
 * Usage: bun scripts/build-hershey-fonts.ts <directory>
 *
 * The directory holds `hershey`, the glyphs in James Hurt's format, and the
 * .hmp files that map ASCII 32 to 126 to glyph numbers, as Paul Bourke
 * distributes them at https://paulbourke.net/dataformats/hershey/.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/** Borland's fonts 1 to 10, by file, and the Hershey font each stands for. */
const FONTS: [string, string][] = [
  ['TRIP', 'romant'],
  ['LITT', 'romans'],
  ['SANS', 'romand'],
  ['GOTH', 'gothgbt'],
  ['SCRI', 'scripts'],
  ['SIMP', 'romans'],
  ['TSCR', 'scriptc'],
  ['LCOM', 'romanc'],
  ['EURO', 'italicc'],
  ['BOLD', 'romant'],
];

const directory = process.argv[2];
if (!directory) throw new Error('Usage: bun scripts/build-hershey-fonts.ts <directory>');

// Each glyph: its number in columns 1-5, its vertex count (with the left and
// right bounds) in 6-8, then the pairs, running on over lines.
const glyphs = new Map<number, string>();
const lines = readFileSync(join(directory, 'hershey'), 'latin1').split(/\r?\n/);
for (let i = 0; i < lines.length; i++) {
  const line = lines[i] ?? '';
  if (!line.trim()) continue;
  const number = Number(line.slice(0, 5)),
    count = Number(line.slice(5, 8));
  let data = line.slice(8);
  while (data.length < count * 2 && i + 1 < lines.length) data += lines[++i] ?? '';
  glyphs.set(number, data.slice(0, count * 2));
}

/** A .hmp file's glyph numbers: single ones, and ranges such as 3001-3026. */
const map = (name: string): number[] =>
  readFileSync(join(directory, `${name}.hmp`), 'latin1')
    .trim()
    .split(/\s+/)
    .flatMap((entry) => {
      const parts = entry.split('-').map(Number);
      const from = parts[0] ?? Number.NaN,
        to = parts[1] ?? from;
      if (Number.isNaN(from)) return [];
      return Array.from({ length: to - from + 1 }, (_, i) => from + i);
    });

const used = new Set<number>();
const fonts = FONTS.map(([file, name]) => {
  const numbers = map(name).slice(0, 95);
  if (numbers.length !== 95) throw new Error(`${name}.hmp maps ${String(numbers.length)} glyphs`);
  numbers.forEach((number) => {
    if (!glyphs.has(number)) throw new Error(`No glyph ${String(number)} for ${name}`);
    used.add(number);
  });
  return `  ${file}: [${numbers.join(', ')}],`;
});
const table = [...used]
  .sort((a, b) => a - b)
  .map((number) => `  ${String(number)}: ${JSON.stringify(glyphs.get(number))},`);

writeFileSync(
  join(import.meta.dirname, '../src/compiler/runtime/hersheyFonts.ts'),
  `// Generated by scripts/build-hershey-fonts.ts.
//
// The Hershey Fonts were originally created by Dr. A. V. Hershey while
// working at the U. S. National Bureau of Standards. The format of the font
// data in this distribution was originally created by James Hurt, Cognition,
// Inc., 900 Technology Park Drive, Billerica, MA 01821.

/** Each glyph: its left and right bounds, then its points, a letter a
 * coordinate counted from R, with " R" lifting the pen. */
export const HERSHEY_GLYPHS: Record<number, string> = {
${table.join('\n')}
};

/** The glyphs for ASCII 32 to 126 of the Hershey font standing for each of
 * Borland's stroked fonts, by its file. */
export const HERSHEY_FONTS: Record<string, number[]> = {
${fonts.join('\n')}
};
`
);
