/** A small slice of the Turbo Pascal online help, shown in the Help window. */
export const HELP_TOPICS: Record<string, { title: string; lines: string[] }> = {
  contents: {
    title: 'Help',
    lines: [
      'Turbo Pascal Help - Table of Contents',
      '',
      '  Compiler directives        Options that control code generation',
      '  Procedures and functions   The standard library routines',
      '  Reserved words             Words that cannot be used as identifiers',
      '  Standard units             System, Crt, Dos, Graph, Printer',
      '  Turbo Pascal Language      Syntax of the language',
      '  Error messages             Compiler and runtime error numbers',
      '',
      'Press Alt+H for the Help menu, Esc to close this window.',
    ],
  },
  reserved: {
    title: 'Reserved words',
    lines: [
      'Turbo Pascal reserved words',
      '',
      '  and       array     asm       begin     case      const',
      '  constructor destructor div    do        downto    else',
      '  end       file      for       function  goto      if',
      '  implementation  in  inherited inline    interface label',
      '  mod       nil       not       object    of        or',
      '  packed    procedure program   record    repeat    set',
      '  shl       shr       string    then      to        type',
      '  unit      until     uses      var       while     with     xor',
    ],
  },
  units: {
    title: 'Standard units',
    lines: [
      'Standard units',
      '',
      '  System     Automatically used by every program',
      '  Crt        Screen, keyboard and sound routines',
      '  Dos        Operating system calls',
      '  Graph      The BGI graphics library',
      '  Printer    Declares the Lst text file',
      '  Overlay    Overlay manager',
    ],
  },
  procedures: {
    title: 'Procedures and functions',
    lines: [
      'Standard procedures and functions',
      '',
      '  Write, WriteLn      Send output to a text file',
      '  Read, ReadLn        Read input from a text file',
      '  Abs, Sqr, Sqrt      Numeric functions',
      '  Ord, Chr, Succ, Pred  Ordinal functions',
      '  Length, Copy, Pos   String handling',
      '  Inc, Dec            Increment and decrement',
      '  New, Dispose        Dynamic memory',
      '  Halt, Exit          Control flow',
    ],
  },
  directives: {
    title: 'Compiler directives',
    lines: [
      'Compiler directives',
      '',
      '  {$R+}  Range checking          {$R-}  off',
      '  {$S+}  Stack checking          {$S-}  off',
      '  {$I+}  I/O checking            {$I-}  off',
      '  {$Q+}  Overflow checking       {$Q-}  off',
      '  {$D+}  Debug information       {$D-}  off',
      '  {$N+}  8087 code               {$N-}  off',
      '  {$I filename}  Include a source file',
    ],
  },
  language: {
    title: 'Turbo Pascal Language',
    lines: [
      'Program structure',
      '',
      '  program Name;',
      '  uses Crt;',
      '  const Pi = 3.14159;',
      '  type TDay = (Mon, Tue, Wed);',
      '  var Count : Integer;',
      '',
      '  procedure Hello;',
      '  begin',
      '    WriteLn(' + "'Hello'" + ');',
      '  end;',
      '',
      '  begin',
      '    Hello;',
      '  end.',
    ],
  },
  errors: {
    title: 'Error messages',
    lines: [
      'Common compiler errors',
      '',
      '   2  Identifier expected',
      '   3  Unknown identifier',
      '   4  Duplicate identifier',
      '  10  Unexpected end of file',
      '  26  Type mismatch',
      '  36  BEGIN expected',
      '  85  ";" expected',
      '',
      'Common runtime errors',
      '',
      ' 106  Invalid numeric format',
      ' 200  Division by zero',
      ' 201  Range check error',
    ],
  },
  using: {
    title: 'Using help',
    lines: [
      'Using the Help system',
      '',
      '  F1           Show help for the current context',
      '  Shift+F1     Show the help index',
      '  Ctrl+F1      Look up the word at the cursor',
      '  Alt+F1       Show the previous help topic',
      '  Esc          Close the Help window',
    ],
  },
};
