/** Static Help text and highlighted links transcribed from the supplied Turbo Pascal gallery.
 * Text remains selectable/navigation data; no reference pixels are rendered at runtime.
 */
export const REFERENCE_HELP: Record<string, string[]> = {
  'Help-2': [
    '                                                ',
    '  ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄                        ',
    '   For More Information                         ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀                        ',
    ' Choose one of these for more information:      ',
    '                                                ',
    '  Using Turbo Pascal windows                    ',
    '  Using the editor                              ',
    '  Find dialog box (text search)                 ',
    '  Replace dialog box                            ',
    '  Edit menu                                     ',
    '  File│Save command                             ',
    '  File│Save As command                          ',
    '  "Block read" (^KR) dialog box                 ',
    '  "Block write" (^KW) dialog box                ',
    '                                                ',
  ],
  'Help-Compiler-Directives': [
    '  Compiler Directives                           ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀                         ',
    '  Compiler Directives:                          ',
    '  Switch Directives                             ',
    '    $A                   (Align Data)           ',
    '    $B                   (Boolean Evaluation)   ',
    '    $D                   (Debug Information)    ',
    '    $F                   (Force Far Calls)      ',
    '    $G                   (Generate 80286 Code)  ',
    '    $I                   (Input/Output-Checking)',
    '    $K                   (Smart Callbacks)      ',
    '    $L                   (Local Symbol Informati',
    '    $N                   (80x87 Numeric Coproces',
    '    $P                   (Open String Parameters',
    '    $Q                   (Overflow Checking)    ',
    '    $R                   (Range-Checking)       ',
  ],
  'Help-Edit-Window': [
    '                                                ',
    '  ▄ The Edit Window                             ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀                            ',
    ' Edit windows are where you type in and edit    ',
    ' your Turbo Pascal code. You can also do the    ',
    ' following in an Edit window:                   ',
    '                                                ',
    '  ■ compile your programs                       ',
    '  ■ run your programs                           ',
    '  ■ read them from disk files                   ',
    '  ■ save them to disk files                     ',
    '                                                ',
    ' You can open as many Edit windows as you want, ',
    ' but Turbo Pascal only numbers the first nine   ',
    ' windows (of any kind) you open.                ',
    '                                                ',
  ],
  'Help-Error-messages': [
    '  ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄                            ',
    '  ▌ error messages ▐                            ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀                            ',
    '  See Also:                                     ',
    '   Run-time error messages                      ',
    '   Compiler error messages 1--99                ',
    '   Compiler error messages 100--162             ',
    '                                                ',
    ' Turbo Pascal generates two kinds of error      ',
    ' messages: compiler error messages and run-time ',
    ' error messages.                                ',
    '                                                ',
    '  Compiler Error Messages                       ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀                       ',
    " If a compiler error occurs when you're         ",
    ' compiling from within the IDE, Turbo Pascal    ',
  ],
  'Help-Language-Elements': [
    '  Borland Pascal Language Elements              ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀            ',
    '                                                ',
    '  Character strings                             ',
    '  Comments                                      ',
    '  Constant declarations                         ',
    '  Directives                                    ',
    '  Expressions                                   ',
    '  Function                                      ',
    '  Functions                                     ',
    '  Identifiers                                   ',
    '  Labels                                        ',
    '  Methods                                       ',
    '  Numbers                                       ',
    '  Operators                                     ',
    '  Procedures                                    ',
  ],
  'Help-List-of-Borland-Pascal-Functions-and-Procedures': [
    '                                                ',
    '   List of Borland Pascal Functions and Procedur',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀',
    '                                                ',
    '   Functions and Procedures A-B                 ',
    '   Functions and Procedures C-D                 ',
    '   Functions and Procedures E-F                 ',
    '   Functions and Procedures G                   ',
    '   Functions and Procedures H                   ',
    '   Functions and Procedures I-L                 ',
    '   Functions and Procedures M-P                 ',
    '   Functions and Procedures Q-R                 ',
    '   Functions and Procedures S-SS                ',
    '   Functions and Procedures ST-T                ',
    '   Functions and Procedures U-Z                 ',
    '                                                ',
  ],
  'Help-Reserved-Words': [
    '  Reserved Words                                ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀                              ',
    ' Reserved words have fixed meanings within the  ',
    ' Turbo Pascal language: You cannot redefine     ',
    ' them.                                          ',
    '                                                ',
    ' In the Borland manuals and in this Help        ',
    ' system, reserved words appear in boldface      ',
    ' type.                                          ',
    '                                                ',
    ' Turbo Pascal is not case sensitive, so you can ',
    ' use upper or lowercase letters for these       ',
    ' reserved words.                                ',
    '                                                ',
    '  and                                           ',
    '  asm                                           ',
  ],
  'Help-Standard-Units': [
    "  Borland Pascal's Standard Units               ",
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀             ',
    '                                                ',
    ' A unit is a collection of constants, data      ',
    ' types, variables, procedures, and functions.   ',
    '                                                ',
    ' Borland Pascal provides the following standard ',
    ' units:                                         ',
    '  Crt                                           ',
    '  Graph                                         ',
    '  Graph3                                        ',
    '  Overlay                                       ',
    '  Printer                                       ',
    '  Strings                                       ',
    '  System                                        ',
    '  Turbo3                                        ',
  ],
  'Help-contents': [
    '  ╔═════════▌ PASCAL HELP CONTENTS ▐═════════╗  ',
    '  ║ How to Use Help                          ║  ',
    '  ║ Menus and Hot Keys                       ║  ',
    '  ║ Editor Commands                          ║  ',
    '  ╟──────────────────────────────────────────╢  ',
    '  ║ Functions and Procedures                 ║  ',
    '  ╟────────────────────┬─────────────────────╢  ',
    '  ║ Built-in Assembler │ Reserved Words      ║  ',
    '  ║ Command Line       │ Sample Programs     ║  ',
    '  ║ Debugging          │ Start-Up Options    ║  ',
    '  ║ Directives         │ Turbo Vision        ║  ',
    '  ║ Error Messages     │ Units               ║  ',
    '  ║ ObjectBrowser      │ Glossary            ║  ',
    '  ║ ObjectWindows      │ Windows API         ║  ',
    '  ╚════════════════════╧═════════════════════╝  ',
    '   ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ ',
  ],
  'Help-general-layout': [
    '  program (reserved word)                       ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀                     ',
    '                                                ',
    ' This is the general layout of a Turbo Pascal   ',
    ' program:                                       ',
    '                                                ',
    '    program          ... ; { Program heading }  ',
    '    uses             ... ; { Uses clause }      ',
    '    label            ... ; { Labels }           ',
    '    const            ... ; { Constants }        ',
    '    type             ... ; { Types }            ',
    '    var              ... ; { Variables}         ',
    '    procedure        ... ; { Procedures }       ',
    '    function         ... ; { Functions }        ',
    '    begin                                       ',
    '       statement;    { Statements }             ',
  ],
  'Help-index': [
    ' Turbo Help Index                               ',
    '                                                ',
    '                                                ',
    '                                                ',
    ' $A                                    $V       ',
    ' $B                                    $W       ',
    ' $C                                    $X       ',
    ' $CAP-EDIT                             $Y       ',
    ' $CAP-MSG                              &        ',
    ' $COL                                  (),asm   ',
    ' $CONFIG                               (xxx)    ',
    ' $D                                    *        ',
    ' $DEFINE                                 TURBO  ',
    ' $DIR()                                  TURBO  ',
    ' $DRIVE()                              +        ',
    ' $E                                      TURBO  ',
  ],
  'Help-welcome-screen': [
    '                                                ',
    "  ▄ Welcome to Turbo Pascal's Online Help       ",
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀  ',
    ' You can learn about Turbo Pascal through this  ',
    ' online Help system.                            ',
    '                                                ',
    '  ■ What you\'re reading right now is a "Help    ',
    '    screen."                                    ',
    '  ■ Most Help screens have some highlighted     ',
    '    items ("Help keywords") on them that lead   ',
    '    to another Help screen.                     ',
    '                                                ',
    '  ┌─────┐ You can use the arrow keys to move    ',
    '  │Arrow│ the cursor from one Help keyword to   ',
    '  └─────┘ another, then press Enter to choose   ',
    '          that item.                            ',
  ],
};

export const REFERENCE_CONTEXT_HELP: Record<string, string[]> = {
  'Help-Editor-options': [
    '                                                ',
    '  ▄ Help on the Editor Options Dialog Box       ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀      ',
    ' The Editor Options dialog box consists of one  ',
    ' group of check box options, one input box, and ',
    ' the standard OK, Cancel, and Help buttons.     ',
    '                                                ',
    '  ┌──────────────────────────┐                  ',
    '  │ Editor Options           │                  ',
    '  │  [X] Create backup file  │                  ',
    '  │  [ ] Insert mode         │                  ',
    '  │  [ ] Auto indent mode    │                  ',
    '  │  [ ] Use tab character   │                  ',
    '  │  [ ] Optimal fill        │                  ',
    '  │  [ ] Backspace unindents │                  ',
  ],
  'Help-Mouse-Options': [
    '                                                ',
    '  ▄ Help on the Mouse Options dialog box        ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀       ',
    ' This dialog box consists of one set of radio   ',
    ' buttons, one check box, one slider bar, and    ',
    ' the standard buttons OK, Cancel, and Help.     ',
    '                                                ',
    ' You use the settings in this dialog box to     ',
    ' customize the Control+right mouse button       ',
    ' actions in the Turbo Pascal environment.       ',
    '                                                ',
    '  ┌────────────────────────────┐                ',
    '  │ Control+Right Mouse Button │                ',
    '  │  ( ) Nothing               │                ',
    '  │  (.) Topic search          │                ',
  ],
  'Help-Preferences': [
    '                                                ',
    '  ▄ Help on the Preferences Dialog Box          ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀         ',
    ' The Preferences dialog box consists of three   ',
    ' sets of radio buttons, two groups of check box ',
    ' options, and the standard OK, Cancel, and Help ',
    ' buttons.                                       ',
    '                                                ',
    '  ┌──────────────────┐                          ',
    '  │ Screen sizes     │                          ',
    '  │  ( ) 25 lines    │                          ',
    '  │  ( ) 43/50 lines │                          ',
    '  └──────────────────┘                          ',
    ' The Screen Size radio buttons specify whether  ',
    ' the Turbo Pascal environment screen displays   ',
  ],
  'Turbo-Help-Add-Breakpoints': [
    '                                                ',
    '  ▄ Help on the Add Breakpoints dialog box      ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀     ',
    ' The Add Breakpoints dialog box is where you    ',
    ' add breakpoints. Whenever your running program ',
    ' encounters a breakpoint, it will stop with a   ',
    ' run bar positioned on the line with the        ',
    ' breakpoint.                                    ',
    '                                                ',
    ' Information not complete in this version of    ',
    ' Help.                                          ',
    '                                                ',
    '                                                ',
    '                                                ',
    '                                                ',
  ],
  'Turbo-Help-Compiler-Options': [
    '                                                ',
    '  ▄ Help on the Compiler Options dialog box     ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀    ',
    ' The Compiler Options dialog box consists of    ',
    ' four groups of check boxes, and the standard   ',
    ' OK, Cancel, and Help buttons.                  ',
    '                                                ',
    ' If you are using BP, there is an additional    ',
    ' list box with a pick list and some additional  ',
    ' options in the other check boxes.              ',
    '                                                ',
    '                                                ',
    '   Compiler Settings for:      BP and BPW Only  ',
    ' The following options are available in the     ',
    ' list box:                                      ',
  ],
  'Turbo-Help-Debugger': [
    '                                                ',
    '  ▄ Help on the Debugger Dialog Box             ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀            ',
    ' The Debugger dialog box consists of three      ',
    ' groups of check boxes, one set of radio        ',
    ' buttons, and the standard OK, Cancel, and Help ',
    ' buttons.                                       ',
    '                                                ',
    ' Real Mode Target                               ',
    '  ┌──────────────────┐                          ',
    '  │ Debugging        │                          ',
    '  │  [ ] Integrated  │                          ',
    '  │  [ ] Standalone  │                          ',
    '  │                  │                          ',
    '  │ Display swapping │                          ',
  ],
  'Turbo-Help-Directories': [
    '                                                ',
    '  ▄ Help on the Directories dialog box          ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀         ',
    ' The Directories dialog box consists of five    ',
    ' input boxes and the standard OK, Cancel, and   ',
    ' Help buttons.                                  ',
    '                                                ',
    ' With the options in this dialog box, you tell  ',
    ' Turbo Pascal where to find the files it needs  ',
    ' to compile, link, and output executable files. ',
    '                                                ',
    '  ┌─ EXE and TPU Directory ──────────────┐      ',
    '  │                                      │      ',
    '  └──────────────────────────────────────┘      ',
    ' The EXE and TPU Directory input box specifies  ',
  ],
  'Turbo-Help-Evaluate-and-Modify': [
    '                                                ',
    '  ▄ Help on the Evaluate and Modify dialog box  ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ ',
    ' The Evaluate and Modify dialog box contains    ',
    ' three input boxes, the standard Cancel and     ',
    ' Help buttons, and two additional buttons       ',
    ' (Evaluate and Modify).                         ',
    '                                                ',
    '  ┌─ Expression ─────────────────────────┐      ',
    '  │                                      │      ',
    '  └──────────────────────────────────────┘      ',
    ' The Expression input box shows the word at the ',
    ' cursor in the Edit window; that word is the    ',
    ' default watch expression.                      ',
    '                                                ',
  ],
  'Turbo-Help-Find-Error': [
    '                                                ',
    '  ▄ Help on the Find Error dialog box           ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀          ',
    ' The Find Error dialog box consists of an input ',
    ' box with a history list, and the standard OK,  ',
    ' Cancel, and Help buttons.                      ',
    '                                                ',
    '  ┌───────────────╥──────────────────────────┐  ',
    '  │ Error Address ║                          │  ',
    '  └───────────────╨──────────────────────────┘  ',
    '                                                ',
    ' When a run-time error occurs, the program      ',
    " gives the error's memory location (segment and ",
    ' offset).                                       ',
    '                                                ',
  ],
  'Turbo-Help-Find-Procedure': [
    '                                                ',
    '  ▄ Help on the Find Procedure dialog box       ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀      ',
    ' The Find Procedure dialog box consists of an   ',
    ' input box with a history list, and the         ',
    ' standard OK, Cancel, and Help buttons.         ',
    '                                                ',
    ' The way the Find Procedure dialog box works is ',
    ' similar to the way the Find dialog works,      ',
    " except that, with Find Procedure, you're       ",
    ' searching for the declaration of a procedure,  ',
    ' rather than for instances of its use.          ',
    '                                                ',
    ' You must be debugging to be able to use this   ',
    ' command.                                       ',
  ],
  'Turbo-Help-Go-to-Line': [
    '                                                ',
    '  ▄ Help on the Go to Line Number dialog box    ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀   ',
    ' The Go to Line Number dialog box consists of   ',
    ' an input box with a history list, and the      ',
    ' standard OK, Cancel, and Help buttons.         ',
    '                                                ',
    ' You use the Go to Line Number dialog box to    ',
    ' find the line number you need.                 ',
    '                                                ',
    '  ┌───────────────────────╥───────────┬───┐     ',
    '  │ Enter new line number ║           │   │     ',
    '  └───────────────────────╨───────────┴───┘     ',
    ' Type the number of the line you want, or pick  ',
    ' a previously entered line number from the      ',
  ],
  'Turbo-Help-Linker': [
    '                                                ',
    '  ▄ Help on the Linker Dialog Box               ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀              ',
    ' The Linker dialog box consists of two sets of  ',
    ' radio buttons and the standard OK, Cancel, and ',
    ' Help buttons.                                  ',
    '                                                ',
    '  ┌───────────────┐                             ',
    '  │ Map file      │                             ',
    '  │  ( ) Off      │                             ',
    '  │  ( ) Segments │                             ',
    '  │  ( ) Public   │                             ',
    '  │  ( ) Detailed │                             ',
    '  └───────────────┘                             ',
    ' The Map File set of radio buttons determines   ',
  ],
  'Turbo-Help-Memory-Sizes': [
    '                                                ',
    '  ▄ Help on the Memory Sizes Dialog Box         ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀        ',
    ' The Memory Sizes dialog box consists of three  ',
    ' groups of input boxes and the standard OK,     ',
    ' Cancel, and Help buttons.                      ',
    '                                                ',
    '  Real Mode Target                              ',
    '  ┌──────────────────────╥─────────┐            ',
    '  │ Stack Size           ║ 16384   │            ',
    '  │ Low Heap Limit       ║ 0       │            ',
    '  │ High Heap Limit      ║ 655360  │            ',
    '  └──────────────────────╨─────────┘            ',
    '                                                ',
    ' The Stack Size input box is where you specify  ',
  ],
  'Turbo-Help-Primary-File': [
    '                                                ',
    '  ▄ Help on the Primary File dialog box         ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀        ',
    ' The Primary File dialog box contains an input  ',
    ' box, a file list, a file information panel,    ',
    ' and the standard OK, Cancel and Help buttons,  ',
    ' plus a Clear button and a history list.        ',
    '                                                ',
    '  ┌─ Primary Program File ──────────┐           ',
    '  │                                 │           ',
    '  └─────────────────────────────────┘           ',
    ' This input box is where you enter the name of  ',
    ' the .PAS file to be compiled, or the file-name ',
    ' mask for the Files list box.                   ',
    '                                                ',
  ],
  'Turbo-Help-Program-Parameters': [
    '                                                ',
    '  ▄ Help on the Program Parameters dialog box   ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀   ',
    ' The Program Parameters dialog box consists of  ',
    ' an input box and the standard OK, Cancel, and  ',
    ' Help buttons.                                  ',
    '                                                ',
    '  ┌─ Parameters ─────────────────────────┐      ',
    '  │                                      │      ',
    '  └──────────────────────────────────────┘      ',
    ' The Parameters input box is where you enter    ',
    ' the parameters that you want Turbo Pascal to   ',
    ' pass to your running program.                  ',
    '                                                ',
    " You don't need to enter the program name in    ",
  ],
  'Turbo-Help-Replace': [
    '                                                ',
    '  ▄ Help on the Replace dialog box              ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀             ',
    ' The Replace dialog box contains two input      ',
    ' boxes with associated history lists, three     ',
    ' sets of radio buttons, one group of check      ',
    ' boxes, the standard OK, Cancel, and Help       ',
    ' buttons, and a Change All button.              ',
    '                                                ',
    ' Most components of the Replace dialog box are  ',
    ' identical to those in the Find dialog box.     ',
    '                                                ',
    '  ┌──────────────╥───────────────────┬───┐      ',
    '  │ Text to find ║                   │   │      ',
    '  └──────────────╨───────────────────┴───┘      ',
  ],
  'Turbo-Help-Tools': [
    '  ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄                            ',
    '   Tools dialog box                             ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀                            ',
    ' The Tools dialog box is where you can          ',
    "   ■ review the programs you've already set up  ",
    '     as transfer programs                       ',
    '   ■ add new transfer programs                  ',
    '   ■ edit or delete existing ones               ',
    '                                                ',
    '  ┌─ Program Titles ────────┐                   ',
    '  │   ~GREP                ■│                   ',
    '  │   ~Turbo Assembler     ▒│                   ',
    '  │   Turbo ~Debugger      ▒│                   ',
    '  │   Turbo ~Profiler      ▒│                   ',
    '                                                ',
  ],
  'Turbo-Help': [
    '                                                ',
    '  ▄ Help on the Retrieve Options Dialog Box     ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀    ',
    ' The Retrieve Options dialog box consists of an ',
    ' input box, a file list box, an information     ',
    ' panel, and the standard OK, Cancel, and Help   ',
    ' buttons.                                       ',
    '                                                ',
    ' This dialog box is where you retrieve the      ',
    ' settings you previously saved in a .TP file    ',
    ' with the Save Options command.                 ',
    '                                                ',
    ' If the Desktop File option (.DSK) in the       ',
    ' Preferences dialog box is set to either        ',
    ' Current Directory or Config File Directory,    ',
  ],
  'Turbo-help-colors-dialog-box': [
    '                                                ',
    '  ▄ Help on the Colors dialog box               ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀              ',
    ' The Colors dialog box consists of two list     ',
    ' boxes, a text display area, the standard OK,   ',
    ' Cancel, and Help buttons, and the following:   ',
    '                                                ',
    '  ■ On color and black-and-white systems, it    ',
    '    also contains two color palettes.           ',
    '  ■ On monochrome systems, it contains a set    ',
    '    of radio buttons instead of the palettes.   ',
    '                                                ',
    ' This dialog box is where you can change the    ',
    ' colors of different parts ("views") of the     ',
    ' IDE.                                           ',
  ],
  'Turbo-help-startup-options': [
    '                                                ',
    '  ▄ Help on the Startup Options dialog box      ',
    '  ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀     ',
    ' The Startup Options dialog box consists of one ',
    ' group of check boxes, two input boxes, and the ',
    ' standard OK, Cancel, and Help buttons.         ',
    '                                                ',
    ' ■ NOTE: The changes that you make in this      ',
    ' dialog box are written directly to TURBO.EXE   ',
    " or BP.EXE and don't take effect until the next ",
    ' time you load the IDE.                         ',
    '                                                ',
    '  ┌──────────────────────────┐                  ',
    '  │ [X] Dual Monitor Support │                  ',
    '  │ [X] Graphics Screen Save │                  ',
  ],
};

/** [document row, first column, character count, VGA foreground] link/emphasis runs. */
export const REFERENCE_HELP_EMPHASIS: Record<string, [number, number, number, number][]> = {
  'Help-2': [
    [6, 2, 5, 14],
    [6, 8, 5, 14],
    [6, 14, 6, 14],
    [6, 21, 7, 14],
    [7, 2, 5, 14],
    [7, 8, 3, 14],
    [7, 12, 6, 14],
    [8, 2, 4, 14],
    [8, 7, 6, 14],
    [8, 14, 3, 14],
    [8, 18, 5, 14],
    [8, 24, 7, 14],
    [9, 2, 7, 14],
    [9, 10, 6, 14],
    [9, 17, 3, 14],
    [10, 2, 4, 14],
    [10, 7, 4, 14],
    [11, 2, 9, 14],
    [11, 12, 7, 14],
    [12, 2, 9, 14],
    [12, 12, 2, 14],
    [12, 15, 7, 14],
    [13, 2, 6, 14],
    [13, 9, 5, 14],
    [13, 15, 5, 14],
    [13, 21, 6, 14],
    [13, 28, 3, 14],
    [14, 2, 6, 14],
    [14, 9, 6, 14],
    [14, 16, 5, 14],
    [14, 22, 6, 14],
    [14, 29, 3, 14],
  ],
  'Help-Compiler-Directives': [
    [2, 2, 8, 14],
    [2, 11, 10, 14],
    [3, 2, 6, 14],
    [3, 9, 10, 14],
    [4, 4, 2, 14],
    [4, 25, 6, 14],
    [4, 32, 5, 14],
    [5, 4, 2, 14],
    [5, 25, 8, 14],
    [5, 34, 11, 14],
    [6, 4, 2, 14],
    [6, 25, 6, 14],
    [6, 32, 12, 14],
    [7, 4, 2, 14],
    [7, 25, 6, 14],
    [7, 32, 3, 14],
    [7, 36, 6, 14],
    [8, 4, 2, 14],
    [8, 25, 9, 14],
    [8, 35, 5, 14],
    [8, 41, 5, 14],
    [9, 4, 2, 14],
    [9, 25, 23, 14],
    [10, 4, 2, 14],
    [10, 25, 6, 14],
    [10, 32, 10, 14],
    [11, 4, 2, 14],
    [11, 25, 6, 14],
    [11, 32, 6, 14],
    [11, 39, 9, 14],
    [12, 4, 2, 14],
    [12, 25, 6, 14],
    [12, 32, 7, 14],
    [12, 40, 8, 14],
    [13, 4, 2, 14],
    [13, 25, 5, 14],
    [13, 31, 6, 14],
    [13, 38, 10, 14],
    [14, 4, 2, 14],
    [14, 25, 9, 14],
    [14, 35, 9, 14],
    [15, 4, 2, 14],
    [15, 25, 16, 14],
  ],
  'Help-Edit-Window': [
    [7, 4, 7, 14],
    [8, 4, 3, 14],
  ],
  'Help-Editor-options': [
    [9, 5, 3, 14],
    [9, 9, 6, 14],
    [9, 16, 6, 14],
    [9, 23, 4, 14],
    [10, 5, 1, 14],
    [10, 7, 1, 14],
    [10, 9, 6, 14],
    [10, 16, 4, 14],
    [11, 5, 1, 14],
    [11, 7, 1, 14],
    [11, 9, 4, 14],
    [11, 14, 6, 14],
    [11, 21, 4, 14],
    [12, 5, 1, 14],
    [12, 7, 1, 14],
    [12, 9, 3, 14],
    [12, 13, 3, 14],
    [12, 17, 9, 14],
    [13, 5, 1, 14],
    [13, 7, 1, 14],
    [13, 9, 7, 14],
    [13, 17, 4, 14],
    [14, 5, 1, 14],
    [14, 7, 1, 14],
    [14, 9, 9, 14],
    [14, 19, 9, 14],
  ],
  'Help-Error-messages': [
    [4, 3, 8, 14],
    [4, 12, 5, 14],
    [4, 18, 8, 14],
    [5, 3, 8, 14],
    [5, 12, 5, 14],
    [5, 18, 8, 14],
    [5, 27, 5, 14],
    [6, 3, 8, 14],
    [6, 12, 5, 14],
    [6, 18, 8, 14],
    [6, 27, 8, 14],
  ],
  'Help-Language-Elements': [
    [3, 2, 9, 14],
    [3, 12, 7, 14],
    [4, 2, 8, 14],
    [5, 2, 8, 14],
    [5, 11, 12, 14],
    [6, 2, 10, 14],
    [7, 2, 11, 14],
    [8, 2, 8, 14],
    [9, 2, 9, 14],
    [10, 2, 11, 14],
    [11, 2, 6, 14],
    [13, 2, 7, 14],
    [14, 2, 9, 14],
    [15, 2, 10, 14],
  ],
  'Help-List-of-Borland-Pascal-Functions-and-Procedures': [
    [4, 3, 9, 14],
    [4, 13, 3, 14],
    [4, 17, 10, 14],
    [4, 28, 3, 14],
    [5, 3, 9, 14],
    [5, 13, 3, 14],
    [5, 17, 10, 14],
    [5, 28, 3, 14],
    [6, 3, 9, 14],
    [6, 13, 3, 14],
    [6, 17, 10, 14],
    [6, 28, 3, 14],
    [7, 3, 9, 14],
    [7, 13, 3, 14],
    [7, 17, 10, 14],
    [7, 28, 1, 14],
    [8, 3, 9, 14],
    [8, 13, 3, 14],
    [8, 17, 10, 14],
    [8, 28, 1, 14],
    [9, 3, 9, 14],
    [9, 13, 3, 14],
    [9, 17, 10, 14],
    [9, 28, 3, 14],
    [10, 3, 9, 14],
    [10, 13, 3, 14],
    [10, 17, 10, 14],
    [10, 28, 3, 14],
    [11, 3, 9, 14],
    [11, 13, 3, 14],
    [11, 17, 10, 14],
    [11, 28, 3, 14],
    [12, 3, 9, 14],
    [12, 13, 3, 14],
    [12, 17, 10, 14],
    [12, 28, 4, 14],
    [13, 3, 9, 14],
    [13, 13, 3, 14],
    [13, 17, 10, 14],
    [13, 28, 4, 14],
    [14, 3, 9, 14],
    [14, 13, 3, 14],
    [14, 17, 10, 14],
    [14, 28, 3, 14],
  ],
  'Help-Mouse-Options': [
    [12, 4, 13, 14],
    [12, 18, 5, 14],
    [12, 24, 6, 14],
  ],
  'Help-Preferences': [
    [9, 4, 6, 14],
    [9, 11, 5, 14],
  ],
  'Help-Reserved-Words': [
    [14, 2, 3, 14],
    [15, 2, 3, 14],
  ],
  'Help-Standard-Units': [
    [8, 2, 3, 14],
    [9, 2, 5, 14],
    [10, 2, 6, 14],
    [11, 2, 7, 14],
    [12, 2, 7, 14],
    [13, 2, 7, 14],
    [14, 2, 6, 14],
    [15, 2, 6, 14],
  ],
  'Help-contents': [
    [1, 4, 3, 14],
    [1, 8, 2, 14],
    [1, 11, 3, 14],
    [1, 15, 4, 14],
    [2, 4, 5, 14],
    [2, 10, 3, 14],
    [2, 14, 3, 14],
    [2, 18, 4, 14],
    [3, 4, 6, 14],
    [3, 11, 8, 14],
    [5, 4, 9, 14],
    [5, 14, 3, 14],
    [5, 18, 10, 14],
    [7, 4, 8, 14],
    [7, 13, 9, 14],
    [7, 25, 8, 14],
    [7, 34, 5, 14],
    [8, 4, 7, 14],
    [8, 12, 4, 14],
    [8, 25, 6, 14],
    [8, 32, 8, 14],
    [9, 4, 9, 14],
    [9, 25, 8, 14],
    [9, 34, 7, 14],
    [10, 4, 10, 14],
    [10, 25, 5, 14],
    [10, 31, 6, 14],
    [11, 4, 5, 14],
    [11, 10, 8, 14],
    [11, 25, 5, 14],
    [12, 4, 13, 14],
    [12, 25, 8, 14],
    [13, 4, 13, 14],
    [13, 25, 7, 14],
    [13, 33, 3, 14],
  ],
  'Help-general-layout': [
    [7, 29, 4, 14],
    [8, 29, 6, 14],
    [9, 29, 9, 14],
    [10, 29, 5, 14],
    [11, 29, 9, 14],
    [12, 29, 10, 14],
    [13, 29, 9, 14],
    [15, 23, 10, 14],
  ],
  'Help-index': [
    [4, 1, 2, 14],
    [4, 39, 2, 14],
    [5, 1, 2, 14],
    [5, 39, 2, 14],
    [6, 1, 2, 14],
    [6, 39, 2, 14],
    [7, 1, 9, 14],
    [7, 39, 2, 14],
    [8, 1, 8, 14],
    [8, 39, 1, 14],
    [9, 1, 4, 14],
    [9, 39, 6, 14],
    [10, 1, 7, 14],
    [10, 39, 5, 14],
    [11, 1, 2, 14],
    [11, 39, 1, 15],
    [12, 1, 7, 14],
    [12, 41, 5, 14],
    [13, 1, 6, 14],
    [13, 41, 5, 14],
    [14, 1, 8, 14],
    [14, 39, 1, 15],
    [15, 1, 2, 14],
    [15, 41, 5, 14],
  ],
  'Help-welcome-screen': [],
  'Turbo-Help-Add-Breakpoints': [],
  'Turbo-Help-Compiler-Options': [],
  'Turbo-Help-Debugger': [
    [11, 5, 1, 14],
    [11, 7, 1, 14],
    [11, 9, 10, 14],
    [12, 5, 1, 14],
    [12, 7, 1, 14],
    [12, 9, 10, 14],
    [14, 4, 7, 14],
    [14, 12, 8, 14],
  ],
  'Turbo-Help-Directories': [
    [11, 5, 3, 14],
    [11, 9, 3, 14],
    [11, 13, 3, 14],
    [11, 17, 9, 14],
  ],
  'Turbo-Help-Evaluate-and-Modify': [[8, 5, 10, 14]],
  'Turbo-Help-Find-Error': [
    [4, 12, 7, 14],
    [4, 20, 4, 14],
    [8, 4, 5, 14],
    [8, 10, 7, 14],
  ],
  'Turbo-Help-Find-Procedure': [[8, 24, 4, 14]],
  'Turbo-Help-Go-to-Line': [
    [11, 4, 5, 14],
    [11, 10, 3, 14],
    [11, 14, 4, 14],
    [11, 19, 6, 14],
  ],
  'Turbo-Help-Linker': [
    [8, 4, 3, 14],
    [8, 8, 4, 14],
  ],
  'Turbo-Help-Memory-Sizes': [
    [9, 4, 5, 14],
    [9, 10, 4, 14],
    [9, 25, 1, 14],
    [9, 27, 5, 14],
    [10, 4, 3, 14],
    [10, 8, 4, 14],
    [10, 13, 5, 14],
    [10, 25, 1, 14],
    [10, 27, 1, 14],
    [11, 4, 4, 14],
    [11, 9, 4, 14],
    [11, 14, 5, 14],
    [11, 25, 1, 14],
    [11, 27, 6, 14],
  ],
  'Turbo-Help-Primary-File': [
    [6, 27, 7, 14],
    [6, 35, 4, 14],
    [8, 5, 7, 14],
    [8, 13, 7, 14],
    [8, 21, 4, 14],
  ],
  'Turbo-Help-Program-Parameters': [[7, 5, 10, 14]],
  'Turbo-Help-Replace': [
    [10, 27, 4, 14],
    [13, 4, 4, 14],
    [13, 9, 2, 14],
    [13, 12, 4, 14],
  ],
  'Turbo-Help-Tools': [
    [9, 5, 7, 14],
    [9, 13, 6, 14],
  ],
  'Turbo-Help': [
    [10, 10, 4, 14],
    [10, 15, 7, 14],
    [12, 8, 7, 14],
    [12, 16, 4, 14],
    [12, 21, 6, 14],
    [13, 1, 11, 14],
    [13, 13, 6, 14],
    [13, 20, 3, 14],
  ],
  'Turbo-help-colors-dialog-box': [],
  'Turbo-help-startup-options': [
    [13, 4, 3, 14],
    [13, 8, 4, 14],
    [13, 13, 7, 14],
    [13, 21, 7, 14],
    [14, 4, 3, 14],
    [14, 8, 8, 14],
    [14, 17, 6, 14],
    [14, 24, 4, 14],
  ],
};
